healthlocker/healthlocker

demos.md
A first pass for the agenda for the demo today.
Still missing:
+ Order of demo runthrough
Linked to issue https://github.com/healthlocker/healthlocker/issues/15
=> First pass of demo agenda for today

web/templates/layout/app.html.eex, web/templates/post/new.html.eex
Links in tachyons for styling & replaces the content UI
=> Post integration

priv/repo/migrations/20170127144415_add_field_to_posts.exs, test/models/post_test.exs, web/controllers/post_controller.ex, web/models/post.ex, web/router.ex, web/templates/post/index.html.eex, web/templates/post/new.html.eex, web/templates/post/show.html.eex
Displays posts as 'Story' cards #17 #8 
All stories can be viewed on `/posts`, new stories can be made in `/posts/new` and individual stories can be expanded and viewed on `posts/{id}`
Ready for review
=> Content integration

test/controllers/post_controller_test.exs, test/controllers/tip_controller_test.exs, test/models/post_test.exs, test/support/fixtures.ex, web/controllers/page_controller.ex, web/controllers/post_controller.ex, web/controllers/tip_controller.ex, web/models/post.ex, web/templates/post/index.html.eex, web/templates/post/show.html.eex
This updates the UI to only contain a single field, changes the schema for the posts table, and displays stories in /posts if the content field from the table contains #story
=> Update content ui

web/templates/page/index.html.eex
=> Add clause for case of no stories being present

web/templates/page/index.html.eex
=> Fix tips on homepage #68

test/models/post_test.exs, web/templates/page/index.html.eex, web/templates/post/index.html.eex, web/templates/post/show.html.eex, web/templates/support/index.html.eex, web/templates/tip/index.html.eex, web/views/tip_view.ex
Removes some unnecessary text, realigns some fields, resizes sections
=> Styling fixes

demos.md
As per #72, this adds a proposed demo run-through order for today's demo.
=> Adds demo run-through for today's demo

web/templates/page/index.html.eex, web/templates/post/new.html.eex
At per #74, some small tweaks ahead of the demo:
+ Add a 'See more stories' link to the homepage
+ Temporarily remove the 'location' and 'photo' button from the new post page
+ Make the size of the font a little smaller in the textarea on the new post page
Thanks for the review @katbow!
=> Small fixes ahead of demo

README.md, priv/repo/migrations/20170208141649_add_fields_to_users.exs, test/controllers/page_controller_test.exs, test/controllers/post_controller_test.exs, test/controllers/tip_controller_test.exs, test/controllers/user_controller_test.exs, test/models/post_test.exs, test/models/user_test.exs, test/support/test_helpers.ex, web/controllers/user_controller.ex, web/models/user.ex, web/router.ex, web/templates/layout/app.html.eex, web/templates/user/form.html.eex, web/templates/user/signup2.html.eex, web/templates/user/signup3.html.eex
Users can go through the full flow of the Name & email form -> password, security Q & A -> T&Cs, privacy & request for data access.
=> Signup flow

config/prod.exs, web/templates/coping_strategy/edit.html.eex, web/templates/coping_strategy/index.html.eex, web/templates/goal/edit.html.eex
Fix small styling and link issues in goals
Change scheme to work on healthlocker.uk since it is set up for http
=> Goal style fix

README.md, priv/repo/migrations/20170222112433_add_number_to_users.exs, test/controllers/account_controller_test.exs, test/controllers/post_controller_test.exs, test/models/user_test.exs, test/views/account_view_test.exs, test/views/coping_strategy_view_test.exs, test/views/goal_view_test.exs, test/views/tip_view_test.exs, test/views/toolkit_view_test.exs, test/views/user_view_test.exs, web/controllers/account_controller.ex, web/models/user.ex, web/router.ex, web/templates/account/index.html.eex, web/templates/support/index.html.eex, web/views/account_view.ex
User account allows for editing/updating information #116
=> Account screen

README.md, priv/repo/migrations/20170222112433_add_number_to_users.exs, test/controllers/account_controller_test.exs, test/controllers/coping_strategy_controller_test.exs, test/controllers/goal_controller_test.exs, test/controllers/post_controller_test.exs, test/models/user_test.exs, test/views/account_view_test.exs, test/views/coping_strategy_view_test.exs, test/views/goal_view_test.exs, test/views/tip_view_test.exs, test/views/toolkit_view_test.exs, test/views/user_view_test.exs, web/controllers/account_controller.ex, web/models/user.ex, web/router.ex, web/templates/account/consent.html.eex, web/templates/account/index.html.eex, web/templates/support/index.html.eex, web/views/account_view.ex
#121 
Users can update their consent to share data for research
=> Account consent update

web/templates/like/index.html.eex
=> Internal server error at healthlocker.uk

test/controllers/account_controller_test.exs, web/controllers/account_controller.ex, web/templates/account/index.html.eex, web/templates/account/profile.html.eex, web/templates/account/slam_connected.html.eex
Create form for displaying to slam connected users
SLaM SUs have more data in their profile than non-connected users, so the form that is rendered depends on if the current user is slam connected or not.
=> Info messages

test/controllers/account_controller_test.exs, web/controllers/account_controller.ex, web/router.ex, web/templates/account/nhs_help.html.eex, web/templates/account/slam.html.eex
This displays information to the user for how to find their NHS number #137.
The information is displayed on a separate page from the form to connect to slam and the user can go back by clicking close at the bottom.
=> Finding NHS number

test/controllers/post_controller_test.exs, web/controllers/post_controller.ex, web/models/post.ex, web/models/posts_likes.ex, web/models/user.ex, web/templates/like/index.html.eex
Fixes #168 
I made a booboo and pushed to master 🙈 . I reverted back so the commits in this branch were behind, so there is only one commit to get it back up to speed. I realised after that I could've cherry-picked the likes from master.
Andddd I also protected master now so that it requires PRs before merging.
=> Fix internal server error on likes

README.md, test/controllers/term_controller_test.exs, test/views/term_view_test.exs, web/controllers/term_controller.ex, web/router.ex, web/templates/term/index.html.eex, web/templates/user/signup3.html.eex, web/views/term_view.ex
Add set up for terms and conditions so copy can be added in quickly as soon as it's available #114
=> Terms and conditions

test/controllers/privacy_controller_test.exs, test/views/privacy_view_test.exs, web/controllers/privacy_controller.ex, web/router.ex, web/templates/privacy/index.html.eex, web/templates/user/signup3.html.eex, web/views/privacy_view.ex
Add set up for privacy statement so copy can be added in quickly as soon as it's available #115
=> Privacy statement

web/templates/like/index.html.eex, web/templates/page/index.html.eex
Styling the article lists of stories and tips
Fixes #202
=> styling to stories and tips lists #202

web/templates/page/index.html.eex, web/templates/post/index.html.eex
Styled the individual posts page to have the same style as the stories and tips lists
=> styling of individual posts page issue #204

web/templates/layout/app.html.eex
Added some minor styling for side nav
=> Side nav style

web/templates/account/index.html.eex, web/templates/account/profile.html.eex
Applied Tachyons greyscale styles to:
input fields + labels
checkbox
button
=> Added greyscale styling to profile tab on account (1/3) #218

web/static/css/app.css, web/templates/account/consent.html.eex, web/templates/account/index.html.eex, web/templates/account/menu.html.eex, web/templates/account/profile.html.eex, web/templates/account/security.html.eex
Apply styles to checkbox, label and button
Fixes #225
=> Consent tab (3/3)

web/templates/layout/app.html.eex
For #172 
About link can be added once it is merged in.
=> Add footer with links

web/static/css/app.css, web/templates/layout/app.html.eex
Adds a beta banner #94 
Can add in link to feedback once that is complete
=> Beta Banner

.travis.yml, web/templates/coping_strategy/form.html.eex, web/templates/coping_strategy/show.html.eex, web/templates/goal/form.html.eex, web/templates/goal/show.html.eex, web/views/coping_strategy_view.ex, web/views/goal_view.ex
Update goals and coping strategies text formatting.
#209 #210 #212 #237
fixes #245
=> Copy changes

web/templates/page/index.html.eex
Add an intro to healthlocker on the homescreen which only shows to logged out users #261
=> Home screen intro

web/static/css/app.css, web/templates/coping_strategy/form.html.eex, web/templates/coping_strategy/new.html.eex, web/templates/goal/form.html.eex, web/templates/goal/new.html.eex, web/templates/toolkit/index.html.eex
Applied styling of the 'new goals/strategies' pages to-
- style in text area box
- buttons
This pull request contains the toolkit page (tools #244) and footer (#248)
=> new 'goals' and 'strategies' page

web/templates/coping_strategy/index.html.eex, web/templates/goal/index.html.eex, web/templates/layout/app.html.eex
- Style the goals list page and coping strategy pages to be in line with the rest of the app's style
- added padding to footer
Fixes 262
Pull request include also the last pull requests code #248 #250 #258
=> Style goals list and coping strategy pages

test/controllers/page_controller_test.exs, web/templates/page/privacy.html.eex, web/templates/page/terms.html.eex
For #114 and #115
Adds content copy with formatting to each page
=> Add content for T&Cs and Privacy statement

test/controllers/user_controller_test.exs, web/models/user.ex, web/templates/user/signup3.html.eex
Adds and changes text to reflect #269
=> Signup fix

web/templates/account/profile.html.eex, web/templates/account/slam.html.eex
Styles page for connecting account to slam #288
=> Slam styling

SLaM-interoperability-notes.md
Adds the notes from yesterday's meeting with SLaM to the repo.
@nelsonic Could you please check through for accuracy and merge?
=> Adds notes for SLaM interoperability meeting

web/templates/account/edit_security.html.eex, web/templates/account/profile.html.eex, web/templates/layout/app.html.eex, web/templates/user/form.html.eex, web/templates/user/signup2.html.eex, web/templates/user/signup3.html.eex
I was going through issues this morning to add test labels etc where necessary and wanted to tie off old issues so they can be closed. 
Addresses changes for #127 #12 #133 #255
=> Misc fixes

test/controllers/login_controller_test.exs, web/controllers/login_controller.ex
The user can no longer log in if they have not completed all steps of sign up.
Fixes #347
=> Fix login flow

web/static/js/tracker.js, web/templates/coping_strategy/show.html.eex, web/templates/feedback/index.html.eex, web/templates/goal/show.html.eex, web/views/component_view.ex, web/views/coping_strategy_view.ex, web/views/goal_view.ex
Displays goals & coping strategies date added as DD/MM/YYYY instead of YYYY-MM-DD
#210 #212 
Fixes covered send button on iphone 5 #381
=> Date format fix

README.md, web/static/css/app.css, web/templates/account/consent.html.eex, web/templates/account/edit_password.html.eex, web/templates/account/edit_security.html.eex, web/templates/account/profile.html.eex, web/templates/account/slam_connected.html.eex, web/templates/coping_strategy/form.html.eex, web/templates/feedback/index.html.eex, web/templates/goal/form.html.eex, web/templates/layout/app.html.eex, web/templates/login/index.html.eex, web/templates/post/new.html.eex, web/templates/sleep_tracker/form.html.eex, web/templates/user/form.html.eex, web/templates/user/signup2.html.eex, web/templates/user/signup3.html.eex, web/views/component_view.ex
Styles error messages (not flash messages yet) and highlights the input where the error occurred.
#360
=> Error styling

web/templates/page/index.html.eex, web/templates/tip/index.html.eex, web/views/component_view.ex, web/views/page_view.ex, web/views/tip_view.ex
=> wrapping each tip in a link

lib/healthlocker/analytics/event_name_builder.ex, lib/healthlocker/analytics/properties_builder.ex, web/controllers/sleep_tracker_controller.ex
- Creates Night's Sleep Tracked event for analytics tracking
Relates #375
=> Creates Night's Sleep Tracked event for analytics tracking

web/static/css/app.css, web/templates/support/index.html.eex
=> fixing ui issues raised in #314

test/views/component_view_test.exs, test/views/sleep_tracker_view_test.exs, web/views/component_view.ex, web/views/sleep_tracker_view.ex
Better formatting of hours slept
#388
=> Formatting hours

priv/repo/migrations/20170412101634_add_details_to_goals.exs, priv/repo/migrations/20170412101634_add_goals_steps.exs, test/controllers/goal_controller_test.exs, test/models/goal_test.exs, test/models/step_test.exs, web/controllers/goal_controller.ex, web/models/goal.ex, web/models/step.ex, web/static/assets/images/Checkmark.svg, web/static/assets/images/unchecked.svg, web/templates/coping_strategy/show.html.eex, web/templates/goal/form.html.eex, web/templates/goal/show.html.eex
#236 
Up to 5 steps can be added for completing a goal. Remaining steps remain blank, and can be edited and added to.
Steps can be checked off in edit view, with an image displayed to indicate completion in show view
=> Goal detail

test/views/component_view_test.exs, web/static/css/app.css, web/templates/account/menu.html.eex, web/templates/account/slam.html.eex, web/templates/care_plan/index.html.eex, web/templates/coping_strategy/index.html.eex, web/templates/coping_strategy/show.html.eex, web/templates/goal/index.html.eex, web/templates/goal/show.html.eex, web/templates/page/about.html.eex, web/templates/page/index.html.eex, web/templates/page/privacy.html.eex, web/templates/page/terms.html.eex, web/templates/post/index.html.eex, web/templates/sleep_tracker/index.html.eex, web/templates/sleep_tracker/new.html.eex, web/templates/support/index.html.eex, web/templates/tip/index.html.eex, web/templates/toolkit/index.html.eex, web/templates/user/index.html.eex, web/templates/user/new.html.eex, web/templates/user/signup2.html.eex, web/templates/user/signup3.html.eex, web/views/component_helpers/button.ex, web/views/component_helpers/link.ex, web/views/component_view.ex
Fixes that came up just before or after the demo
#369 #363 #370 #369
=> Demo fixes

test/views/sleep_tracker_view_test.exs, web/templates/sleep_tracker/index.html.eex, web/views/sleep_tracker_view.ex
All dates in sleep tracker are meant to be displayed in the more detail section #386
=> Date change

test/models/post_test.exs, web/controllers/page_controller.ex, web/models/post.ex, web/static/assets/images/x_icon.svg, web/static/css/app.css, web/templates/account/nhs_help.html.eex, web/templates/account/profile.html.eex, web/templates/account/security.html.eex, web/templates/account/slam.html.eex, web/templates/account/slam_help.html.eex, web/templates/component/like.html.eex, web/templates/layout/app.html.eex, web/templates/login/index.html.eex, web/templates/page/about.html.eex, web/templates/page/terms.html.eex, web/templates/sleep_tracker/index.html.eex, web/templates/user/form.html.eex, web/templates/user/index.html.eex, web/templates/user/signup3.html.eex, web/views/component_helpers/link.ex, web/views/component_view.ex
For #449 #447 #376 #370 
Changes close nav icon to white
Tips & stories no longer prompt to sign up or log in
Random top & story displayed on home page
Use components for missed links & buttons
=> Home page changes

.gitignore, config/config.exs, config/test.exs, lib/healthlocker/analytics.ex, lib/healthlocker/endpoint.ex, mix.exs, mix.lock, test/controllers/goal_controller_test.exs, test/controllers/login_controller_test.exs, test/controllers/message_controller_test.exs, test/features/require_login_test.exs, test/features/view_homepage_test.exs, test/plugs/require_login_test.exs, test/support/feature_case.ex, test/test_helper.exs, web/controllers/account_controller.ex, web/controllers/care_plan_controller.ex, web/controllers/coping_strategy_controller.ex, web/controllers/goal_controller.ex, web/controllers/login_controller.ex, web/controllers/message_controller.ex, web/controllers/post_controller.ex, web/controllers/sleep_tracker_controller.ex, web/controllers/user_controller.ex, web/plugs/auth.ex, web/plugs/require_login.ex, web/router.ex, web/templates/layout/app.html.eex, web/templates/login/index.html.eex, web/views/layout_view.ex
Previously we were copy and pasting an `authenticate` plug into controllers that required a user. This PR adds a new plug `RequireLogin`, then in the routes we separate which routes require login and which one's don't. It also adds [`wallaby`](https://github.com/keathley/wallaby) in order to write some feature test for this behaviour. 
As this is just a refactor there shouldn't be any change to current behaviour, @katbow can you have a look at the changes to `Router` to see if there's anything I've missed?
This should fix the issues #425 and #413
=> Authenticate plug

web/templates/layout/app.html.eex
- Changes footer from aqua to dark blue background color. #371 
- Changes 'Terms and conditions' link to 'Terms of Service' #348
=> Footer styling

web/templates/goal/index.html.eex, web/templates/layout/app.html.eex, web/templates/page/index.html.eex
- #359 Moves 'Add new' goal button to be aligned on the right.
- Adds classes to burger and 'X' buttons so that the cursor is a pointer when hovered above these.
=> Button Styling

web/templates/layout/app.html.eex
Adds caseload to menu for clinicians #38 
@Cleop I assigned you since you recently changed this, to make sure it is still functional the same way you intended 👍
=> Clinician menu

web/static/css/app.css, web/templates/caseload/index.html.eex, web/templates/goal/form.html.eex
- Styles clinician arrows to be yellow and bold (still awaiting final svg icon), #354 
- Changes copy from 'Mark as important' to 'Star as important' for important goals, #491
=> Clinician arrows, Star as important

test/controllers/message_controller_test.exs, web/controllers/care_team_controller.ex, web/templates/care_team/index.html.eex, web/templates/care_team/menu.html.eex, web/templates/layout/app.html.eex, web/templates/message/index.html.eex
Adds care team navigation to care team page  and displays care team in burger menu for both SLaM SUs and carers #275
Displays messages section as "Messaging coming soon" to alert the user that development is in progress for this section
=> Care Team nav

web/templates/account/edit_password.html.eex, web/templates/account/edit_security.html.eex, web/templates/coping_strategy/form.html.eex, web/templates/feedback/index.html.eex, web/templates/login/index.html.eex, web/templates/patient/menu.html.eex, web/templates/patient/messages.html.eex, web/templates/user/form.html.eex, web/templates/user/signup2.html.eex, web/templates/user/signup3.html.eex
Adds a placeholder tab to clinician view of patients to show messaging is in development #546
=> Clinician tabs

test/controllers/caseload_controller_test.exs, web/controllers/caseload_controller.ex, web/templates/caseload/index.html.eex
Change to epjs_user to user full name with forename & surname #548
=> Epjs names

test/features/service_user_message_test.exs, web/controllers/care_team/message_controller.ex, web/templates/care_team/message/coming_soon.html.eex
We only have Rooms for carers atm, so if a service user navigates to messaging, show them a coming soon message.
=> Show a coming soon message, rather than 404.

test/controllers/caseload_controller_test.exs, web/controllers/caseload_controller.ex
Gets user info from id & epjsuser from slam_id in users table #548
=> Caseload fix

test/features/su_connect_slam.exs, web/controllers/account_controller.ex, web/models/user.ex, web/templates/account/slam_connected.html.eex
for #584 
The name of the user will update when they connect to slam.
It will be displayed in account, but will not be editable\
The link to connect as a carer will not be visible to SLaM SUs
=> Update SLaM SU first and last name

priv/repo/migrations/20170511154125_remove_users_name.exs, test/controllers/account_controller_test.exs, test/controllers/care_plan_controller_test.exs, test/controllers/caseload/user_controller_text.exs, test/controllers/caseload_controller_test.exs, test/controllers/coping_strategy_controller_test.exs, test/controllers/goal_controller_test.exs, test/controllers/login_controller_test.exs, test/controllers/post_controller_test.exs, test/controllers/slam_controller_test.exs, test/controllers/sleep_tracker_controller_test.exs, test/controllers/toolkit_controller_test.exs, test/controllers/user_controller_test.exs, test/features/clinician_message_test.exs, test/features/service_user_message_test.exs, test/models/user_test.exs, web/models/user.ex, web/templates/account/profile.html.eex, web/templates/care_team/contact/show.html.eex, web/templates/care_team/index.html.eex, web/templates/caseload/index.html.eex, web/templates/layout/app.html.eex, web/templates/user/form.html.eex, web/views/care_team/message_view.ex, web/views/message_view.ex
#583 #582 
Please merge #609 in first 🙂 
Updates name to first_name & last_name for sign up & account profile
Updates name in tests
Displays first & last name across the site (caseload, care team, messages)
=> Signup & Account names

lib/email.ex, priv/repo/migrations/20170512132357_add_password_reset_to_users.exs, test/controllers/password_controller_test.exs, web/controllers/feedback_controller.ex, web/controllers/password_controller.ex, web/models/user.ex, web/router.ex, web/templates/login/index.html.eex, web/templates/password/edit.html.eex, web/templates/password/new.html.eex, web/views/password_view.ex
#176 
* Form to enter email address for forgotten password
* Email is sent with link including token
* If link is valid (valid unexpired token), then takes user to page for updating password
* If user enters a valid password & matching password confirmation, then the password is updated
* Expired & used tokens are deleted (along with the sent_at date) from the db
* User can log in with new password
=> Forgot password

mix.exs, test/views/sleep_tracker_view_test.exs, test/views/tip_view_test.exs, web/channels/room_channel.ex, web/controllers/account_controller.ex, web/controllers/caseload_controller.ex, web/controllers/goal_controller.ex, web/templates/layout/_segment.html.eex, web/templates/layout/app.html.eex, web/templates/sleep_tracker/index.html.eex, web/views/component_helpers/button.ex, web/views/layout_view.ex, web/views/message_view.ex, web/views/post_view.ex, web/views/sleep_tracker_view.ex
corrects most of the warnings picked up on in #393
=> Correct warnings

web/templates/coping_strategy/edit.html.eex, web/templates/coping_strategy/form.html.eex
for #554 
Can delete coping strategy on edit page, but not on any other page
=> Delete coping strategies link

web/templates/page/about.html.eex, web/templates/page/carer_help.html.eex, web/templates/page/index.html.eex, web/templates/page/slam_help.html.eex
update copy on carer and slam help #308 
stop images from getting too small on pages about #576
stop images from being stretched on home page in mobile view #611
=> changes text and the positioning of images 

web/controllers/care_team/contact_controller.ex, web/controllers/care_team/room_controller.ex, web/controllers/caseload/room_controller.ex, web/controllers/support_controller.ex, web/templates/care_team/contact/show.html.eex, web/templates/room/_room.html.eex
add disclaimer text for service user and carer messaging #586 #587
=> Disclaimer text

web/templates/caseload/index.html.eex
Fixes misaligned caseload in https://github.com/healthlocker/healthlocker/issues/604
=> Clearfix caseload carers list.

web/controllers/page_controller.ex, web/router.ex, web/templates/layout/app.html.eex
`@rooms` was not available in eex template (it's in app.html.eex).
Added it so it's available in all logged in & logged out routes.
#642
=> Post & tip fix

test/features/caseload_users_test.exs, test/test_helper.exs
Added a bunch of feature tests around the clinician caseload. Could probably do with adding a few tests around the Goals.
=> Caseload feature tests

web/controllers/caseload/user_controller.ex, web/templates/caseload/user/details.html.eex, web/templates/caseload/user/interactions.html.eex, web/templates/caseload/user/menu.html.eex, web/templates/caseload/user/tracking.html.eex
adds 'tracking' to caseload user menu and allows a clinician to be able to see the sleep tracker data of a service user. #612 #622
=> Clinicians able to see sleep tracker

config/config.exs, test/features/caseload_users_test.exs, test/features/clinician_message_test.exs, test/views/component_view_test.exs, web/controllers/caseload/user_controller.ex, web/templates/care_team/contact/show.html.eex, web/templates/caseload/index.html.eex, web/templates/caseload/room/show.html.eex, web/templates/caseload/user/carer_menu.html.eex, web/templates/caseload/user/details.html.eex, web/templates/caseload/user/interactions.html.eex, web/templates/caseload/user/menu.html.eex, web/templates/caseload/user/messages.html.eex, web/views/caseload/user_view.ex, web/views/component_view.ex
Carer goals do not display for clinician #625 
Only shows messages, details & contacts when clinician is viewing a carer.
Displays messages by default for carer
If clinician goes to url for carer goals, gets message that they are not available for carers.
=> Carer goals

test/features/care_team_test.exs, test/features/service_user_message_test.exs, test/views/component_view_test.exs, web/templates/care_team/contact/show.html.eex, web/views/component_view.ex
Fixes error on contact page & adds feature tests to ensure care team sections load as expected #625
=> Contact error

test/controllers/caseload/user_controller_text.exs, test/features/caseload_users_test.exs, web/controllers/caseload/user_controller.ex, web/templates/caseload/user/tracking.html.eex, web/templates/sleep_tracker/index.html.eex, web/templates/sleep_tracker/sleep_data.html.eex
adds previous and next to Tracking in clinician view. #612
=> Clinician sleep tracker

web/templates/room/_room.html.eex
#586 #587 #591
Clinician disclaimer was overtaking carer and SU disclaimer.
=> Only show disclaimer for clinicians

test/views/tracker_view_test.exs, web/controllers/caseload/user_controller.ex, web/controllers/tracker_controller.ex, web/static/js/tracker.js, web/templates/symptom_tracker/new.html.eex, web/views/tracker_view.ex
copy change #560 
update line graph display #698 
correct variables being passed into merge tracking data #626 #672
=> Graph display

test/controllers/page_controller_test.exs, web/templates/layout/app.html.eex
For #365:
Logged out now says:
Home
About
Tips
Stories
Get support
Sign up
Log in
Logged in now says:
Goals and tracking
Care team *(if they have a care team)*
Tips
Stories
Get support
Account
Log out
=> Burger menu reshuffle

web/templates/coping_strategy/index.html.eex, web/templates/goal/index.html.eex, web/templates/tracker/index.html.eex
Only display warning message if user is a slam user. #305
=> Only display warning message if user is a slam user. #305

web/controllers/caseload/user_controller.ex, web/controllers/tracker_controller.ex, web/templates/symptom_tracker/new.html.eex, web/templates/tracker/tracking_data.html.eex, web/views/tracker_view.ex
allow users and clinicians to view daily diary entries in tracker #627 #614 
copy change #560
=> Daily diary

web/templates/sleep_tracker/form.html.eex
Adds sleep tips section to the bottom of the sleep tracker input #651 
Links open in a new tab.
=> Sleep tips

priv/repo/migrations/20170526095112_edit_diaries_table.exs, priv/repo/migrations/20170526100948_edit_sleep_tracker_notes.exs, priv/repo/migrations/20170526101039_edit_symptom_tracker_notes.exs, priv/repo/migrations/20170526102024_edit_create_goals_notes.exs
allow text area fields to save more than 255 characters. #614 #561
=> Textareas database type

web/static/css/app.css, web/templates/caseload/user/details.html.eex
Pushes carer details down as they were hidden underneath the menu #678
=> Carer menu fix

web/static/css/app.css, web/templates/caseload/index.html.eex
Fixes styling in caseload for people using IE. #678
=> Fixes styling in caseload for people using IE. #678

web/templates/layout/app.html.eex, web/templates/toolkit/index.html.eex
#711 checks if the current user has a slam id to display care plan summary 
#619 adjusts slam logo
=> Only show care plan to slam connected users

web/static/js/tracker.js
fixes bug with graph. #613 #683
=> fixes bug with graph. #613 #683

web/static/css/app.css, web/templates/caseload/user/interactions.html.eex, web/templates/coping_strategy/index.html.eex, web/templates/coping_strategy/show.html.eex, web/templates/goal/index.html.eex, web/templates/goal/show.html.eex
- Bug found in #680 about long links not wrapping. Solves this across goals and coping strategies.
=> Wraps links onto second line when they're very long

priv/repo/migrations/20170526151054_add_c4c_to_users.exs, test/controllers/account_controller_test.exs, test/lib/slam/connect_slam_test.exs, web/controllers/account_controller.ex, web/models/user.ex, web/templates/account/consent.html.eex, web/templates/account/slam.html.eex
#566 
Adds c4c to users
Adds c4c to connecting to slam & to account consent
Updates in database for the user
=> c4c in connecting to slam

web/controllers/tracker_controller.ex
#741 
Should fix internal server error on tracking
=> Tracking overview error fix

test/controllers/feedback_controller_test.exs, web/templates/feedback/index.html.eex, web/templates/post/index.html.eex, web/views/post_view.ex
feedback page copy changes #723
create functions to return first 50 words of a story. #486
=> Copy change

README.md, editing-select-options.md, markdown-syntax.md, tracking-feature.md
#757
Separates instructions into separate READMEs and links in main README. 
Adds a description for HL
Describes the tracking features in full detail with screen shots
Updates technical instructions to include necessary seeds
Adds links to relevant pages and technical documentation
=> Documentation updates

web/templates/account/profile.html.eex, web/templates/account/slam.html.eex, web/templates/account/slam_connected.html.eex, web/templates/login/index.html.eex, web/templates/message/_message.html.eex, web/templates/post/index.html.eex, web/templates/room/_room.html.eex, web/templates/slam/_form.html.eex, web/views/post_view.ex
Red disclaimer text for messaging for service users and carers #720
Update carer link when someone is already connected as a carer #674
Remove vertical padding on text inputs so they can be seen in safari #734
Increase space between forgot password link and log in button #747
Style messages tab #751
Update functions for posts to only display the header and first paragraph. #486
=> Sprint 12 finishing touches

web/templates/tip/index.html.eex
#785 /tips styling wasn't updated in the same way home page was.
=> Fix stretched out images in tips

priv/read_only_repo/migrations/20170608154614_rename_tables.exs, web/models/epjs_clinician.ex, web/models/epjs_patient_address_details.ex, web/models/epjs_team_member.ex, web/models/epjs_user.ex
Update table names to match schema #818
=> Epjs review

web/templates/account/profile.html.eex, web/templates/account/slam_connected.html.eex, web/templates/page/carer_help.html.eex, web/templates/page/slam_help.html.eex, web/templates/page/terms.html.eex, web/templates/support/index.html.eex
Change copy for slam in missed areas.
#819 slam help text
#820 carer help text
#821 account connected text
#814 get support text
#811 terms text
#773 link text in account
=> Change SLaM site wide

web/controllers/sleep_tracker_controller.ex, web/templates/coping_strategy/form.html.eex, web/templates/page/about.html.eex, web/templates/page/privacy.html.eex, web/templates/slam/_form.html.eex, web/templates/sleep_tracker/form.html.eex, web/templates/tip/index.html.eex
@nelsonic this turned into a "how much can I do in the last 20 minutes branch" so it's a bit of everything 😉 :
#829 form typo
#828 dreaded slam reference
#817 removing target _blanks
#812 capitalisation in privacy statement
#808 alignment of tips
#816 don't allow users to fill in sleep data if already tracker, alert beforehand
=> Slam typos

web/templates/feedback/index.html.eex
One more quick one. horizontal padding for #789
=> Fix horizontal padding on feedback form #789

web/controllers/care_team/room_controller.ex
Update clinicians who can view a room with a carer/service user if the clinicians list ever updates #59
=> Update clinician rooms

config/prod.exs
update variable names for production. #841
=> update variable names for production

config/prod.exs
remove ssl true as no longer needed. #874 #841
=> update prod env 

config/prod.exs
for https://github.com/healthlocker/healthlocker/issues/874
trying to reduce the uncertainty as much as possible so we can deploy with `edeliver`
=> make config/prod.exs Healthlocker.Repo config *identical* to dev.exs 

mix.exs, web/views/component_view.ex
add earmark to list of applications #887
solution to try and fix issue #885 where txt files are not being loaded
=> Edeliver build

web/views/component_view.ex
trying to fix loading of .txt files in prod. #885
solution suggested here...
https://stackoverflow.com/questions/43414104/read-files-in-phoenix-in-production-mode
=> loading .txt files in prod. #885

web/views/component_view.ex
update path files are read from to resolve #885
=> load txt files in staging 

mix.exs
add to project applications #894
=> add to project applications

lib/healthlocker/decrypt_user.ex, web/controllers/caseload_controller.ex
adds functionality which redirects a user if they try to use a encoded url with an already expired token #911
=> Expiry token

lib/healthlocker/slam/connect_carer.ex, lib/healthlocker/slam/connect_slam.ex
fix bug where SU cannot connect to care team if they have the same person in it more than once. #909
=> fix bug where SU cannot connect to care team

lib/healthlocker/slam/disconnect_slam.ex, test/lib/slam/disconnect_slam_test.exs
update function to allow for more than one clinician_room to be deleted at a time #928
=> Slam disconnections 

web/controllers/care_team/room_controller.ex
change the way we check if clinician_rooms need to be updated in the controller #918
adds cases which check if clinicians need to be added to clinician_rooms, removed from clinician_rooms, both added to and removed from clinician_rooms or if nothing needs to change.
=> Care team rooms

web/static/js/app.js, web/templates/account/profile.html.eex, web/templates/page/about.html.eex, web/templates/page/carer_help.html.eex, web/templates/page/nhs_help.html.eex, web/templates/page/slam_help.html.eex, web/templates/slam/_form.html.eex, web/templates/support/index.html.eex
content changes as requested in #895
open links in new tabs, create function to close current tab and style p tags to look like link #924
=> Content close button

web/controllers/care_team/room_controller.ex
=> update id to "Staff_ID" #918

web/templates/account/slam.html.eex
make link open in new tab #924.
Missed in error in commit #932
=> make link open in new tab #924

.deliver/config, README.md, mix.exs, nginx.config
update configuration file for #841
=> Updating Configuration Settings for Edeliver and NGINX for Azure Deployment

test/controllers/account_controller_test.exs, web/templates/account/consent.html.eex
=> consent edit, add useage

web/templates/user/signup3.html.eex
=> Sign up edit to consent

web/templates/goal/edit.html.eex
#978   added some compy
#984 added grey dividers
=> goals edit

web/templates/caseload/user/carer_menu.html.eex
=> carer menu Communications

test/features/service_user_message_test.exs, web/templates/care_team/menu.html.eex
=> SU_carer_menuedit_Communications

web/templates/account/slam_connected.html.eex
=> Update to Disconnect Link Text

web/templates/page/disconnect.html.eex
=> Copy Change to Disconnect Page

web/templates/sleep_tracker/form.html.eex
=> Copy Addition to Sleep Tracker

web/templates/room/_room.html.eex
=> notes disclaimer edits

web/templates/support/index.html.eex
=> Content Changes to Get Support

web/templates/coping_strategy/form.html.eex
https://github.com/healthlocker/healthlocker/issues/772
I want the list with the '-' to display as a list with dashes not a bullet pointed list.
=> coping strategy tweaks

web/templates/feedback/index.html.eex
=> feedback page edits

web/templates/coping_strategy/form.html.eex
=> move Rethink section above the Save button.

web/templates/page/about.html.eex
=> Add Video Links to About

rel/config.exs
=> update rel/config #1027

lib/email.ex
send feedback email to hl team as well as existing email #939
=> send feedback email to hl team #939

web/templates/goal/edit.html.eex
=> remove extra text boxes

web/templates/room/_room.html.eex
Adjust messages to be under menu. They were moved up and hidden behind it
Signed in as service user:
#865
=> Message fix

web/templates/goal/edit.html.eex
=> remove 'each'

priv/read_only_repo/migrations/20170831145530_update_help_others.exs, test/controllers/care_plan_controller_test.exs, test/controllers/symptom_controller_test.exs, test/features/caseload_users_test.exs, test/lib/slam/connect_slam_test.exs, test/views/component_view_test.exs, web/controllers/care_plan_controller.ex, web/controllers/care_team/room_controller.ex, web/controllers/caseload/user_controller.ex, web/controllers/coping_strategy_controller.ex, web/controllers/login_controller.ex, web/controllers/sleep_tracker_controller.ex, web/templates/care_plan/index.html.eex, web/views/component_view.ex
#42 #1051
* Get all child tables with Repo.all since it is a one to many relationship
* Display all results for each child table under the relevant headings
* Display correct text & formatting for users without a care plan
* Test users with and without a care plan
=> Care plan fix

web/static/css/app.css, web/templates/caseload/user/interactions.html.eex, web/views/tracker_view.ex
#900 Make tick boxes smaller for clinician view of goals
#830 change display of 0 for no days entered/days entered with 0 hours slept.
=> Clincian goals

lib/queries/care_plan_query.ex, web/controllers/care_plan_controller.ex, web/templates/care_plan/index.html.eex
#42 
re ordered it
re named each heading and subheading
added grey line dividers
added a couple of line breaks (between content and where it says assessed by)
added link to goals
added link to coping strategies
#1054 Add changes from #1053
=> Reorder care plan & add links

web/templates/care_plan/index.html.eex
=> accommodation typo

lib/email.ex, test/controllers/password_controller_test.exs, test/views/tracker_view_test.exs, web/controllers/password_controller.ex, web/views/tracker_view.ex
Change link for password reset email #927 
Use same behaviour for attempting to reset password with/without user or if user is clinician #1073 
Display diary timestamp taking into account BST #1071
=> Testing updates

config/prod.exs, web/plugs/auth.ex
Adds session timeout after X minutes of inactivity. The timeout is set as an environment variable in minutes.  #260 
Small change for #1095 as well to change to integer from environment variables.
=> Add session expiry after 30 mins of inactivity #260

config/prod.exs, mix.exs, mix.lock
Logs errors to a file on the server #1080
=> Error logging

config/prod.exs, mix.exs, mix.lock
This reverts commit eb2d9324949a6603cb5275b647ef38bff6665eae, reversing
changes made to aedb2a80def1f54ccf89cb0819a5d3bc3ae4d025.
#1080
=> Revert last merge

test/controllers/symptom_controller_test.exs, test/views/tracker_view_test.exs, web/controllers/symptom_controller.ex, web/views/tracker_view.ex
Change start & end point for recursion & add more tests for other days of week #1110
=> Duplicated tracker day

web/templates/feedback/index.html.eex
=> Change copy for feedback instructions

mix.exs
=> Add dependency to applications #1116

web/templates/coping_strategy/index.html.eex, web/templates/coping_strategy/show.html.eex, web/templates/goal/index.html.eex, web/templates/tracker/tracking_data.html.eex, web/views/coping_strategy_view.ex, web/views/goal_view.ex, web/views/tracker_view.ex
formats the text on goal and tracker overview pages #1123 
updates format_output function to be more flexible #1123
=> Format text

web/controllers/tracker_controller.ex, web/models/sleep_tracker.ex
uses the date_for key to put sleep data in the correct day #1124
=> Sleep for date

web/templates/caseload/user/interactions.html.eex, web/templates/goal/index.html.eex, web/templates/goal/show.html.eex, web/views/caseload/user_view.ex
format goal and coping strategy as expected #1131
display goal steps on a service users goal pages #1132
=> Goal steps

test/controllers/goal_controller_test.exs, web/controllers/goal_controller.ex
order the steps for a goal as requested #1135
=> Order goal steps

test/controllers/tracker_controller_test.exs, web/controllers/tracker_controller.ex, web/models/sleep_tracker.ex
Put correct date in the get_diary_data function calls when called in prev_date and next_date. #1146
Add test for get_diary_data #1146 
Update the last week function to go back 7 days rather than 6 #1150
=> Tracker view bugs

healthlocker.service, healthlocker_service_script.md
create docs for how to create and use script which will restart application on server reboot #1157 #1148
=> script to restart app

web/controllers/caseload/user_controller.ex, web/controllers/coping_strategy_controller.ex, web/static/css/app.css, web/templates/coping_strategy/edit.html.eex, web/templates/goal/edit.html.eex
order goal steps and coping strategies #1143 #1020 
create conformation for deleting goals and coping strategies #213 #977
=> Hl support

web/static/css/app.css, web/templates/diary/form.html.eex, web/templates/login/index.html.eex
update diary page so that text area is larger and bullet points can be hidden/shown #1028
small styling change #719
=> Enhancement

test/controllers/diary_controller_test.exs, web/templates/account/menu.html.eex, web/templates/care_plan/index.html.eex, web/templates/care_team/menu.html.eex, web/templates/coping_strategy/index.html.eex, web/templates/diary/edit.html.eex, web/templates/diary/new.html.eex, web/templates/goal/index.html.eex, web/templates/page/about.html.eex, web/templates/page/privacy.html.eex, web/templates/page/terms.html.eex, web/templates/post/index.html.eex, web/templates/sleep_tracker/new.html.eex, web/templates/support/index.html.eex, web/templates/symptom/new.html.eex, web/templates/tip/index.html.eex, web/templates/tracker/index.html.eex, web/views/component_helpers.ex, web/views/component_helpers/header.ex
Create a `header.ex` to help with updating headers going forward. #1024
=> create header file to help managing headers going forward #1024
