healthlocker/healthlocker

test/controllers/support_controller_test.exs
test/views/support_view_test.exs
web/controllers/support_controller.ex
web/router.ex
web/templates/support/index.html.eex
web/views/post_view.ex
web/views/support_view.ex

Adds a static page displaying all the information for immediate crisis support.
The `Get Support` title may be integrated into a header/navbar
Section which will later need clarification for content is the `App support` section

Crisis support page

---

test/controllers/user_controller_test.exs
web/controllers/auth.ex
web/controllers/login_controller.ex
web/controllers/user_controller.ex
web/templates/coping_strategy/index.html.eex
web/templates/layout/app.html.eex
web/templates/toolkit/index.html.eex

These are a couple of quick fixes @iteles and I noticed when going through the coping strategies flow last night. It redirects to toolkit after logging in/signing up, adds toolkit to drawer menu when logged in, and changes toolkit to images for goals and coping strategies, and separates sign up and login to different lines in the drawer menu.

Strategies clean up

---

.travis.yml

Used the advice from here: https://dockyard.com/blog/2015/12/02/speeding-up-elixir-project-build-times-on-travis-ci
To reduce the build times ~2mins to ~1min 🎉

Cache the build and deps directories in Travis CI.

---

README.md

- Separates README instructions into installation list (for non-technical new users) and command line instructions (for everyone to follow) once initial installation is complete to break down size of instructions.
- Adds line to prevent brew error: `brew link autoconf automake`
- Specifies that postgresql must be installed/ open with a user created to resolve issues #147 #80 
- Indicates readers should enter `y` when prompted by this message:
` Could not find "rebar3", which is needed to build dependency :fs
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use: "mix local.rebar --force") [Yn] `
Fixes #147  #80

Adds detail to README setup instructions for setup from scratch

---

test/controllers/account_controller_test.exs
web/controllers/account_controller.ex
web/router.ex
web/templates/account/index.html.eex
web/templates/account/slam_help.html.eex

This displays information to the user for how and why to connect with SLaM #136. 
The information is displayed on a separate page from the profile and the user can go back by clicking close at the bottom.

Connecting info

---

README.md

- Adds new step 'mix deps.get' to get out of date dependencies in setup.
As recognised in issue #184 which it now fixes.

Adds step 'mix deps.get' to get out of date dependencies in setup

---

web/static/css/app.css
web/templates/account/index.html.eex
web/templates/account/menu.html.eex
web/templates/account/profile.html.eex
web/templates/account/security.html.eex

Styles links on security tab to look like buttons, for clearer 'call to action'.
Fixes #223

Account security tab (2/3)

---

priv/repo/migrations/20170309161933_create_goals.exs
test/controllers/goal_controller_test.exs
test/models/goal_test.exs
web/controllers/goal_controller.ex
web/models/goal.ex
web/models/post.ex

Start on #211. The goals are now added to and get from the goals table instead of posts table, so more fields can be added which are unique to goals.

Set up goals for schema changes

---

web/templates/layout/app.html.eex
web/templates/toolkit/index.html.eex

Addresses #321 
Fixes the size of the icons in toolkit - both were very large and the user needed to scroll down no matter what the screen size to click each icon. The icons are now side by side. 
The header logo was also resized on various devices as part of fixing this issue. There was not much space on the page, even with resizing the icons to a more reasonable size, and adding any more content would likely result in the user still scrolling due to the header taking up so much space (on large screens).

Icon size fix

---

test/controllers/sleep_tracker_controller_test.exs
web/controllers/sleep_tracker_controller.ex
web/router.ex
web/static/js/tracker.js
web/templates/sleep_tracker/index.html.eex
web/views/sleep_tracker_view.ex

For #382 
Data can be viewed for previous or next 7 days
Date has been added to label on x-axis (otherwise it was unclear which Tuesday was meant for what date when scrolling through over time).

Change date range for sleep overview

---

test/controllers/account_controller_test.exs
test/views/component_view_test.exs
web/controllers/account_controller.ex
web/templates/account/edit_security.html.eex
web/templates/sleep_tracker/form.html.eex
web/templates/user/form.html.eex
web/templates/user/signup2.html.eex
web/templates/user/signup3.html.eex
web/views/component_view.ex

#360
The error outline was showing when the page first loaded. There also needed to be a check for changeset actions before adding the class. 
Additionally, some fields were not showing the error because they were not part of the changesets (and instead were a password/security question check). This was fixed by adding an error and an action to the changeset in the controller.

Fixes error outlines

---

web/static/css/app.css
web/templates/layout/app.html.eex

- Rearranges padding so there is no whitespace beneath the footer. 
- Removes unneeded margin on 'Get support' so that the text and pink background show as they should.
- Adds white border on the right on desktop screens (as per the design).
- Reduces the width of the menu display for desktop screens.
- Spaces the links as per the design for desktop with a little extra space between the 'X' and home in comparison to on mobile.
All for #448

Create narrow menu display on desktop

---

web/templates/page/index.html.eex

- Removes like button from stories so #420 can be closed. (Will be replaced separately with a bookmark icon)
- Alters padding from #472 feedback.

Issue fixes

---

web/controllers/care_team/room_controller.ex
web/controllers/caseload/room_controller.ex
web/controllers/caseload/user_controller.ex
web/models/user.ex

In Healthlocker a `User` can have a few different roles:
- Service User (linked to slam)
- Carer (linked to a service user)
This PR adds a helper `User. service_user_for/1` which will return the Service User, for a given User. We then use this in the Caseload controllers to find the correct service user, before querying slam.

Find the service user

---

web/templates/toolkit/index.html.eex

#689 
Reorder icons to be
Goals - Coping Strategies
Care Plan
Sleep/Problem Tracker
Diary/Tracking Overview
Also only just realised the buttons were still not changed here, so switched them to match the site wide button styling #543

Reorder menu in goals & tracking

---

priv/read_only_repo/migrations/20170627095645_add_user_guid.exs
priv/repo/migrations/20170627103813_add_user_guid.exs
test/controllers/caseload_controller_test.exs
test/features/caseload_users_test.exs
test/features/clinician_message_test.exs
web/controllers/caseload/room_controller.ex
web/controllers/caseload/user_controller.ex
web/controllers/caseload_controller.ex
web/models/epjs_team_member.ex
web/models/user.ex
web/router.ex

Sets up clinician flow when arriving to healthlocker via caseload with `userData` param. #869 epic #838 
* Add user_guid to schemas
* Set up route for caseload index with userData param.
* If user_guid does not exist in HL users & does exist in epjs, add clinician to HL, login, & display caseload
* if user_guid exists in HL, log in clinician and display caseload
* if user_guid does not exist in HL or epjs, redirect to homepage with flash message saying authentication failed
* Fixes and adds to relevant tests

Clinician flow

---

web/controllers/password_controller.ex

add check to case statement to not allow clinician's to reset passwords #912.
@reddog at mindwave pointed out that this could be a security risk if clinicians can reset their passwords as someone may be able to gain access to the clinicians email, then log into HL and view sensitive patient info

stop clinician's from resetting passwords #912

---

lib/email.ex
priv/repo/migrations/20170713085039_edit_messages_table.exs

create migration to edit messages table. This will allow for longer messages to be sent in chat rooms #880

send longer messages in chat rooms 

---

web/templates/tip/index.html.eex

As a HEALTHLOCKER user i want to see this link on both:
tips page: healthlocker.uk/tips
each tip tag page, e.g. healthlocker.uk/tips?tag=Connect
#903

Add link to feedback on tips

---

web/templates/care_plan/index.html.eex

For #1050 
Fields cannot be accessed with `table_name["Field_Name"]` behaviour, so has been changed to `table_name."Field_Name".

Fix for accessing fields from care plan

---

deployment_and_ssl.md

#1067 
Adds Healthlocker specific documentation for deploying.
Includes instructions for:
* Installing erlang with odbc
* Installing odbc drivers
* Additional environment variables that need to be added for Healthlocker
* Setting up an account with admin privileges

Deployment documentation

---

deployment_and_ssl.md

Update deployment documentation to include instructions for setting up AppSignal on staging and live servers #1106

Add instructions for configuring AppSignal on staging and live

---

priv/repo/migrations/20171122100745_add_tracker_unique_index.exs
test/controllers/symptom_controller_test.exs
web/controllers/symptom_controller.ex
web/models/symptom.ex

restricts access to adding a new problem tracker when one is already created. #1109

Restrict tracker
